---
- name: Configure a VirtualBox VM for devstack
  hosts: devstack
  user: vagrant
  sudo: True
  gather_facts: False
  tasks:

  - apt: update_cache=yes

  - name: install packages
    apt:  name={{ item }}
    with_items:
      - git
      - git-review
      - python-pip
      - ipython
      - htop
      - nfs-kernel-server
      - libmysqlclient-dev
      - libxml2-dev
      - libxslt1-dev
      - gettext

  - file: dest=/opt/stack state=directory owner=vagrant group=root mode=0755

  - lineinfile: dest=/etc/exports regexp='^\/opt\/stack'
                line='/opt/stack    *(rw,sync,no_root_squash)'
    notify: restart nfs

  - name: install pips
    pip:  name={{ item }}
    with_items:
      - mock
      - virtualenv
      - nose
      - rednose

    # https://bugs.launchpad.net/openstack-ci/+bug/1274135
  - pip: name=tox version=1.6.1

  - lineinfile: dest=/home/vagrant/.bashrc regexp='^export NOSE_REDNOSE'
                line='export NOSE_REDNOSE=1'

  - name: clone devstack
    git:  repo=https://github.com/openstack-dev/devstack
          dest=/home/vagrant/devstack force=no update=no
    sudo: False

  - name: copy localrc
    copy: src=localrc dest=/home/vagrant/devstack/localrc
          force=no owner=vagrant group=vagrant mode=0644

  - git: repo=https://github.com/openstack-infra/os-loganalyze
         dest=/opt/stack/os-loganalyze force=no update=no
    sudo: False

  - copy: src=rc.local dest=/etc/rc.local mode=0755
  - command: /etc/rc.local

  handlers:
  - name: restart nfs
    action: service name=nfs-kernel-server state=restarted
    sudo: True

