---
- name: provision a VM ready for devstack
  hosts: devstack
  user: vagrant
  gather_facts: False
  vars:
    - mangle: openstack@yahoo
  tasks:

  - name: update packages
    sudo: True
    apt:  update_cache=yes

  - name: install packages
    sudo: True
    apt:  name={{ item }}
    with_items:
      - git
      - git-review
      - python-mock
      - python-tox
      - language-pack-en-base

    # http://askubuntu.com/a/17002
  - command: dpkg-reconfigure locales
             creates=/home/vagrant/.reconfigure-locale-done
    sudo: True

  - command: git config --global color.ui true
  - command: git config --global user.name "Darragh O'Reilly"
  - command: git config --global user.email dara2002-{{ mangle }}.com

  - name: clone devstack
    git:  repo=https://github.com/openstack-dev/devstack
          dest=/home/vagrant/devstack force=no update=no

  - name: install localrc
    copy: src=localrc dest=/home/vagrant/devstack/localrc force=no
          owner=vagrant group=vagrant mode=0644
